baseURL = "https://pulsifer.ca"
languageCode = "en-us"
title = 'pulsifer.ca'
theme = "minimal"
disqusShortname = "pulsifer" # delete this to disable disqus comments
googleAnalytics = "UA-73387370-3"

# github pages
publishDir = "docs"
[params]
    author = "Jonathan Pulsifer"
    description = "hi, i'm <a href=\"https://twitter.com/JonPulsifer\">@jonpulsifer</a>"
    githubUsername = "jonpulsifer"
    accent = "#3371e3"
    showBorder = true
    profilePic = "https://gravatar.com/avatar/74de7279f174084ab1d4616e507ba90e?s=400"
    backgroundColor = "#e7e7e7"
    font = "Lato" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "agate"
    highlightLanguages = ["yaml", "go", "json", "shell"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

#[[menu.main]]
#    url = "/post/"
#    name = "Posts"
#    weight = 2

#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jonathan [at] pulsifer.ca"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jonpulsifer"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/JonPulsifer"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jonpulsifer"
    name = "linkedin"
    weight = 4

# [[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
